apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fuel
  name: fuel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fuel
    spec:
      containers:
      - image: fuel:1.0
        name: fuel
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fuel
  name: fuel
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fuel
  type: ClusterIP
status:
  loadBalancer: {}
